version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  lint:
    parameters:
      python-version:
        type: string
    executor:
      name: python/default
      tag: << parameters.python-version >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run pylint --rcfile=pylint.rc beeline
      - run: poetry run pycodestyle beeline --max-line-length=140

  test:
    parameters:
      python-version:
        type: string
    executor:
      name: python/default
      tag: << parameters.python-version >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run coverage run -m beeline.test_suite
      - run: poetry run coverage report --include="beeline/*"
      - run: poetry run coverage html --include="beeline/*"
      - store_artifacts:
          path: htmlcov

  build:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: mkdir -p ~/artifacts
      - run: poetry build
      - run: cp dist/* ~/artifacts
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts
      - store_artifacts:
          path: ~/artifacts

  publish_pypi:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry publish --build -u honeycomb -p ${PYPI_PASSWORD}

  publish_github:
    docker:
      - image: cibuilds/github:0.13.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Artifacts being published"
          command: |
            echo "about to publish to tag ${CIRCLE_TAG}"
            ls -l ~/artifacts/*
      - run: ghr -draft -n ${CIRCLE_TAG} -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ~/artifacts

  push_docs:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout
      - run:
          name: Push docs
          command: ./push_docs.sh

workflows:
  nightly:
    triggers:
          - schedule:
              cron: "0 0 * * *"
              filters:
                branches:
                  only:
                    - main
    jobs:
      - lint: &lint
          matrix: &matrix
            parameters:
              python-version:
                - "3.7"
                - "3.8"
                - "3.9"
                - "3.10"
      - test: &test
          matrix: *matrix
      - build: &build
          requires:
            - lint
            - test

  build_beeline:
    jobs:
      - lint:
          <<: *lint
          filters:
              tags:
                only: /.*/
      - test:
          <<: *test
          filters:
              tags:
                only: /.*/
      - build:
          <<: *build
          filters:
              tags:
                only: /.*/
      - publish_pypi:
          context: Honeycomb Secrets for Public Repos
          requires:
            - build
          filters:
            tags:
              only: /v[0-9].*/
            branches:
              ignore: /.*/
      - publish_github:
          context: Honeycomb Secrets for Public Repos
          requires:
            - build
          filters:
            tags:
              only: /v[0-9].*/
            branches:
              ignore: /.*/
      - push_docs:
          context: Honeycomb Secrets for Public Repos
          requires:
            - publish_pypi
          filters:
            tags:
              only: /v[0-9].*/
            branches:
              ignore: /.*/